// src/routes/_marketing.resources.read.vue-beginner-guide.tsx
import { createFileRoute } from "@tanstack/react-router";
import { ReaderShell, Section, Figure, FAQItem, Callout, Code, type ReaderResource, type TocItem } from "@/components/resources/ReaderShell";

const RESOURCE: ReaderResource = {
  id: "vue-beginner-guide",
  title: "Vue.js — Beginner Guide",
  category: "Web Development",
  difficulty: "Beginner",
  readingTime: "18 min",
  pages: 16,
  lastUpdated: "September 2026",
  tags: ["Vue", "Composition"],
  heroImage: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=1800&q=80",
  heroSubtitle: 'A friendly first tour of Vue.js — SFCs, the Composition API, and shipping your first reactive SPA.',
};

const TOC: TocItem[] = [
  { id: "objectives", label: "Learning Objectives" },
  { id: "prereq", label: "Prerequisites" },
  { id: "toc", label: "Table of Contents" },
  { id: "intro", label: "Introduction" },
  { id: "content", label: "Core Concepts & Detailed Content" },
  { id: "architecture", label: "Architecture & Workflow" },
  { id: "examples", label: "Practical Examples & Enterprise Use Cases" },
  { id: "practices", label: "Best Practices" },
  { id: "mistakes", label: "Common Mistakes" },
  { id: "tips", label: "Tips & Tricks" },
  { id: "compare", label: "Comparison Table" },
  { id: "considerations", label: "Security, Performance & SEO" },
  { id: "summary", label: "Summary & Key Takeaways" },
  { id: "faqs", label: "FAQs" },
  { id: "references", label: "Further Reading & Official References" },
  { id: "disclaimer", label: "Educational Disclaimer" },
];

const RELATED = [
  { title: "Vue.js — Beginner Guide", tag: "Vue", time: "18 min" },
  { title: "Vue.js — Cheat Sheet", tag: "Vue", time: "5 min" },
  { title: "Vue.js — Interview Questions", tag: "Vue", time: "43 min" },
];

export const Route = createFileRoute("/_marketing/resources/read/vue-beginner-guide")({
  head: () => ({
    meta: [
      { title: `${RESOURCE.title} | EduNova AI` },
      { name: "description", content: RESOURCE.heroSubtitle },
      { property: "og:title", content: `${RESOURCE.title} | EduNova AI` },
      { property: "og:description", content: RESOURCE.heroSubtitle },
      { property: "og:image", content: RESOURCE.heroImage },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/resources/read/vue-beginner-guide" }],
  }),
  component: Page,
});

function Page() {
  return (
    <ReaderShell resource={RESOURCE} toc={TOC} related={RELATED}>
      <Section id="objectives" title="Learning Objectives">
        <ul className="list-disc space-y-1 pl-5">
          <li>Master the scope of the <b>Beginner Guide</b> — practical, production-ready Vue.js.</li>
          <li>Author Single File Components (SFCs) with <code>&lt;script setup&gt;</code> and TypeScript.</li>
          <li>Use the Composition API — <code>ref</code>, <code>reactive</code>, <code>computed</code>, <code>watch</code>, and composables.</li>
          <li>Compose apps with Vue Router (lazy routes, guards) and Pinia (typed stores).</li>
          <li>Optimize performance with code splitting, Suspense, and rendering discipline.</li>
          <li>Ship SSR / SSG apps with Nuxt, and deploy Vue apps to production.</li>
        </ul>
      </Section>

      <Section id="prereq" title="Prerequisites">
        <ul className="list-disc space-y-1 pl-5">
          <li>Comfort with modern JavaScript / TypeScript (ES modules, arrow functions, generics).</li>
          <li>Node.js 20+ and a package manager (npm, pnpm, or Bun) installed locally.</li>
          <li>Basic HTML, CSS, and HTTP knowledge; familiarity with the terminal.</li>
        </ul>
      </Section>

      <Section id="toc" title="Table of Contents">
        <ol className="list-decimal space-y-1 pl-5 text-sm text-muted-foreground">
          <li>Introduction to Vue.js and the ecosystem</li>
          <li>Vite, Vue CLI, project structure, and TypeScript integration</li>
          <li>Single File Components — <code>&lt;template&gt;</code>, <code>&lt;script setup&gt;</code>, <code>&lt;style&gt;</code></li>
          <li>Reactive data, methods, computed properties, and watchers</li>
          <li>Directives — <code>v-if</code>, <code>v-show</code>, <code>v-for</code>, <code>v-model</code>, <code>v-bind</code>, <code>v-on</code></li>
          <li>Event handling, conditional and list rendering</li>
          <li>Composition API — <code>setup()</code>, <code>ref()</code>, <code>reactive()</code>, <code>computed()</code>, <code>watch()</code>, <code>watchEffect()</code></li>
          <li>Composables and reusable logic</li>
          <li>Options API and migration to Composition API</li>
          <li>Component communication — props, emits, slots, provide / inject</li>
          <li>Dynamic components, async components, and <code>&lt;KeepAlive&gt;</code></li>
          <li>Custom directives</li>
          <li>Vue Router — nested, dynamic, lazy routes and navigation guards</li>
          <li>State management — Pinia, Vuex, modular stores, and persistence</li>
          <li>Forms — binding, validation, custom inputs, dynamic forms</li>
          <li>HTTP — Fetch, Axios, REST, authentication, error handling</li>
          <li>Styling — scoped CSS, CSS Modules, Tailwind, Sass, CSS variables</li>
          <li>SSR — Nuxt.js, SSG, hydration, and SEO</li>
          <li>Performance — lazy loading, code splitting, rendering optimization</li>
          <li>Testing — Vitest, Vue Test Utils, Cypress, Playwright</li>
          <li>Security — authentication, authorization, XSS prevention, secure APIs</li>
        </ol>
      </Section>

      <Section id="intro" title="Introduction">
        <p>Vue.js is an approachable, performant, and versatile framework for building modern user interfaces. It combines a fine-grained reactivity system, Single File Components, and the Composition API to scale from small widgets to enterprise SPAs — with Nuxt.js layering SSR, SSG, and full-stack conventions on top. This resource — <b>Vue.js — Beginner Guide</b> — is self-contained: A friendly first tour of Vue.js — SFCs, the Composition API, and shipping your first reactive SPA.</p>
        <Callout tone="info" title="Vue in one line">Vue = reactive data + SFCs + Composition API + Pinia + Vue Router — a batteries-included frontend platform.</Callout>
        <Figure src="https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=1400&q=80" caption="Figure 1 — Vue.js architecture — reactivity system, SFCs, and the Composition API compose reactive SPAs." />
      </Section>

      <Section id="content" title="Core Concepts & Detailed Content">
        <ul className="list-disc space-y-1 pl-5">
          <li><b>Foundations</b> — what is Vue, ecosystem, Vue CLI, Vite, project structure, SFCs, TypeScript integration.</li>
          <li><b>Core concepts</b> — templates, reactive data, methods, computed properties, watchers, event handling, conditional and list rendering.</li>
          <li><b>Composition API</b> — <code>setup()</code>, <code>ref</code>, <code>reactive</code>, <code>computed</code>, <code>watch</code>, <code>watchEffect</code>, lifecycle hooks, composables.</li>
          <li><b>Options API</b> — <code>data</code>, <code>methods</code>, <code>computed</code>, <code>watch</code>, lifecycle hooks, and migration to Composition API.</li>
          <li><b>Components</b> — props, emits, slots, provide / inject, dynamic and async components, <code>&lt;KeepAlive&gt;</code>.</li>
          <li><b>Directives</b> — built-ins (<code>v-if</code>, <code>v-show</code>, <code>v-for</code>, <code>v-model</code>, <code>v-bind</code>, <code>v-on</code>) and custom directives.</li>
          <li><b>Routing</b> — Vue Router: nested, dynamic, lazy routes and navigation guards.</li>
          <li><b>State management</b> — Pinia (recommended), Vuex (legacy), global vs modular stores, persistence.</li>
          <li><b>Forms</b> — <code>v-model</code>, validation, custom inputs, dynamic forms.</li>
          <li><b>HTTP</b> — Fetch API, Axios, REST, authentication, retry, error handling.</li>
          <li><b>Styling</b> — scoped CSS, CSS Modules, Tailwind, Sass, CSS variables.</li>
          <li><b>SSR & meta frameworks</b> — Nuxt.js, SSR, SSG, hydration.</li>
          <li><b>Performance</b> — lazy loading, code splitting, virtual DOM, rendering optimization, bundle analysis.</li>
          <li><b>Testing</b> — Vitest, Vue Test Utils, Cypress, Playwright.</li>
          <li><b>Security</b> — authentication, authorization, XSS prevention, secure APIs.</li>
          <li><b>Enterprise</b> — folder structure, clean architecture, reusable components, design systems, scalable apps.</li>
        </ul>
      </Section>

      <Section id="architecture" title="Architecture & Workflow">
        <pre className="overflow-x-auto rounded-lg border border-border/60 bg-muted/40 p-4 text-xs leading-relaxed">
{`Browser
   │
   ▼
[Vue Router]  ── guards / lazy chunks
   │
   ▼
[Root App]  ── <App />  (SFC + <script setup>)
   │        │
   │        ├── Pinia store  → state / getters / actions
   │        └── Composables  → useAuth() / useFetch() / useX()
   ▼
[Reactivity System]  ── refs / reactive → Proxy tracking
   │
   ▼
[Virtual DOM diff]  → efficient DOM updates
   │
   ▼
Nuxt (optional)  ── SSR / SSG / hydration / routing conventions`}
        </pre>
        <Code>{`<!-- Posts.vue — SFC with <script setup>, Composition API + fetch -->
<script setup lang="ts">
import { ref, computed, onMounted } from "vue";

interface Post { id: number; title: string; }

const posts = ref<Post[]>([]);
const query = ref("");
const filtered = computed(() =>
  posts.value.filter(p => p.title.toLowerCase().includes(query.value.toLowerCase()))
);

onMounted(async () => {
  const res = await fetch("/api/posts");
  posts.value = await res.json();
});
</script>

<template>
  <input v-model="query" placeholder="Filter" />
  <ul>
    <li v-for="p in filtered" :key="p.id">{{ p.title }}</li>
  </ul>
</template>`}</Code>
      </Section>

      <Section id="examples" title="Practical Examples & Enterprise Use Cases">
        <Figure src="https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1400&q=80" caption="Figure 2 — Enterprise Vue.js application — Pinia stores, Vue Router, composables, and Nuxt SSR." />
        <ul className="list-disc space-y-1 pl-5">
          <li><b>SaaS dashboards</b> — GitLab, Alibaba, and many SaaS products build admin UIs with Vue.</li>
          <li><b>Marketing sites</b> — Nuxt powers SSR/SSG sites with SEO-friendly routes and fast first paint.</li>
          <li><b>Design systems</b> — SFCs + scoped CSS make component libraries easy to share across teams.</li>
          <li><b>Real-time apps</b> — reactivity + WebSockets keep dashboards, chats, and telemetry live.</li>
          <li><b>Auth flows</b> — Pinia stores + Vue Router guards centralize sessions and protected routes.</li>
          <li><b>E-commerce</b> — Nuxt storefronts combine SSG, ISR-like revalidation, and dynamic PDPs.</li>
        </ul>
        <Code>{`// stores/auth.ts — Pinia store with typed state + actions
import { defineStore } from "pinia";
import { ref, computed } from "vue";

export const useAuth = defineStore("auth", () => {
  const token = ref<string | null>(null);
  const user  = ref<{ id: string; email: string } | null>(null);
  const isAuthed = computed(() => !!token.value);

  async function signIn(email: string, password: string) {
    const res = await fetch("/api/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password }),
    });
    if (!res.ok) throw new Error("Invalid credentials");
    const data = await res.json();
    token.value = data.token;
    user.value  = data.user;
  }

  function signOut() {
    token.value = null;
    user.value  = null;
  }

  return { token, user, isAuthed, signIn, signOut };
});`}</Code>
      </Section>

      <Section id="practices" title="Best Practices">
        <ul className="list-disc space-y-1 pl-5">
          <li>Default to <b>Composition API + <code>&lt;script setup&gt;</code></b> with TypeScript for new projects.</li>
          <li>Extract shared logic into <b>composables</b> (<code>useX()</code>) instead of mixins.</li>
          <li>Keep components small and focused; lift shared state into Pinia stores when needed.</li>
          <li>Use <b>Pinia</b> over Vuex; prefer setup-store syntax for typed, testable stores.</li>
          <li>Always provide a stable <code>:key</code> on <code>v-for</code> — never use array index for volatile lists.</li>
          <li>Lazy-load routes and heavy components with dynamic <code>import()</code>.</li>
          <li>Validate every HTTP response and centralize errors in an interceptor / composable.</li>
        </ul>
      </Section>

      <Section id="mistakes" title="Common Mistakes">
        <ul className="list-disc space-y-1 pl-5">
          <li>Losing reactivity by destructuring a <code>reactive()</code> object — use <code>toRefs</code>.</li>
          <li>Mutating props inside a child component — emit an event instead.</li>
          <li>Using array index as <code>:key</code> — leads to subtle rendering bugs.</li>
          <li>Overusing global state — many concerns are better as local <code>ref()</code> or composables.</li>
          <li>Forgetting to unsubscribe from side effects — use <code>onScopeDispose</code> or <code>watchEffect</code> cleanup.</li>
          <li>Mixing Options and Composition API in the same component without a clear reason.</li>
        </ul>
      </Section>

      <Section id="tips" title="Tips & Tricks">
        <ul className="list-disc space-y-1 pl-5">
          <li>Use <code>defineModel()</code> for two-way bound props without boilerplate emits.</li>
          <li>Wrap async components in <code>&lt;Suspense&gt;</code> for declarative loading states.</li>
          <li>Use <code>&lt;Teleport&gt;</code> to render modals / toasts outside the component tree.</li>
          <li>Prefer <code>shallowRef</code> / <code>shallowReactive</code> for large, mostly-static structures.</li>
          <li>Type Pinia stores with the setup-store syntax; getters become typed <code>computed</code>.</li>
        </ul>
      </Section>

      <Section id="compare" title="Comparison Table">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/60 text-left">
                <th className="py-2 pr-4">Feature / Tool</th>
                <th className="py-2 pr-4">Purpose</th>
                <th className="py-2">When to Use</th>
              </tr>
            </thead>
            <tbody className="[&>tr]:border-b [&>tr]:border-border/40">
              <tr><td className="py-2 pr-4">Composition API</td><td>Modern reactive logic</td><td>Default for new components; better TS and reuse.</td></tr>
              <tr><td className="py-2 pr-4">Options API</td><td>Classic option-based auth</td><td>Legacy code and simple tutorials.</td></tr>
              <tr><td className="py-2 pr-4"><code>ref</code></td><td>Primitive reactivity</td><td>Numbers, strings, single values.</td></tr>
              <tr><td className="py-2 pr-4"><code>reactive</code></td><td>Object reactivity</td><td>Deep reactive objects and stores.</td></tr>
              <tr><td className="py-2 pr-4">Pinia</td><td>State management</td><td>Recommended store for all new apps.</td></tr>
              <tr><td className="py-2 pr-4">Vuex</td><td>Legacy store</td><td>Existing Vuex codebases only.</td></tr>
              <tr><td className="py-2 pr-4">Vue Router</td><td>Client-side routing</td><td>Any multi-page SPA.</td></tr>
              <tr><td className="py-2 pr-4">Nuxt</td><td>SSR / SSG / fullstack</td><td>SEO, fast first paint, hybrid rendering.</td></tr>
              <tr><td className="py-2 pr-4">Vitest</td><td>Unit testing</td><td>Fast, Vite-native test runner.</td></tr>
              <tr><td className="py-2 pr-4">Cypress / Playwright</td><td>E2E testing</td><td>Real-browser flow verification.</td></tr>
            </tbody>
          </table>
        </div>
      </Section>

      <Section id="considerations" title="Security, Performance & SEO">
        <ul className="list-disc space-y-1 pl-5">
          <li><b>Security</b> — trust Vue's HTML escaping, avoid <code>v-html</code> with untrusted input, set CSP, validate on the server.</li>
          <li><b>Performance</b> — lazy routes, <code>&lt;Suspense&gt;</code>, <code>shallowRef</code>, memoized computeds, and image / font optimization.</li>
          <li><b>SEO</b> — Nuxt SSR / SSG, per-route meta with <code>useHead</code>, structured data, canonical URLs.</li>
          <li><b>Deployment</b> — static hosting for SPA; Node hosts for Nuxt SSR; enable gzip / brotli and long-cache hashed assets.</li>
          <li><b>Testing</b> — Vitest + Vue Test Utils for units, Cypress or Playwright for E2E.</li>
        </ul>
      </Section>

      <Section id="summary" title="Summary & Key Takeaways">
        <ul className="list-disc space-y-1 pl-5">
          <li>Vue.js pairs a fine-grained reactivity system with SFCs and the Composition API.</li>
          <li>Default to <code>&lt;script setup&gt;</code> with TypeScript, Pinia stores, and lazy Vue Router routes.</li>
          <li>Extract shared logic into composables; keep components small and cohesive.</li>
          <li>Reach for Nuxt when you need SSR, SSG, or full-stack conventions.</li>
          <li>Test with Vitest + Vue Test Utils and E2E with Cypress or Playwright.</li>
        </ul>
      </Section>

      <Section id="faqs" title="FAQs">
        <FAQItem q="Options API or Composition API?">Composition API for all new components — better TypeScript, reuse, and organization.</FAQItem>
        <FAQItem q="Pinia or Vuex?">Pinia — official, typed, simpler, and the recommended store since Vue 3.</FAQItem>
        <FAQItem q="When should I use Nuxt?">When you need SSR, SSG, file-based routing, or fullstack conventions out of the box.</FAQItem>
        <FAQItem q="Why did my <code>reactive()</code> object stop being reactive?">You destructured it — use <code>toRefs()</code> to keep reactivity when pulling props out.</FAQItem>
        <FAQItem q="Where should I deploy?">Any static host for SPAs; any Node host (Vercel, Netlify, Render, Fly) for Nuxt SSR.</FAQItem>
      </Section>

      <Section id="references" title="Further Reading & Official References">
        <ul className="list-disc space-y-1 pl-5">
          <li><a className="text-primary hover:underline" href="https://vuejs.org/" target="_blank" rel="noreferrer">Vue.js Docs</a> · <a className="text-primary hover:underline" href="https://vuejs.org/api/" target="_blank" rel="noreferrer">Vue API Reference</a></li>
          <li><a className="text-primary hover:underline" href="https://router.vuejs.org/" target="_blank" rel="noreferrer">Vue Router</a> · <a className="text-primary hover:underline" href="https://pinia.vuejs.org/" target="_blank" rel="noreferrer">Pinia</a> · <a className="text-primary hover:underline" href="https://nuxt.com/docs" target="_blank" rel="noreferrer">Nuxt Docs</a></li>
          <li><a className="text-primary hover:underline" href="https://vitejs.dev/" target="_blank" rel="noreferrer">Vite</a> · <a className="text-primary hover:underline" href="https://vitest.dev/" target="_blank" rel="noreferrer">Vitest</a> · <a className="text-primary hover:underline" href="https://test-utils.vuejs.org/" target="_blank" rel="noreferrer">Vue Test Utils</a></li>
          <li><a className="text-primary hover:underline" href="https://developer.mozilla.org/en-US/docs/Web" target="_blank" rel="noreferrer">MDN Web Docs</a> · <a className="text-primary hover:underline" href="https://www.typescriptlang.org/docs/" target="_blank" rel="noreferrer">TypeScript</a></li>
        </ul>
      </Section>

      <Section id="disclaimer" title="Educational Disclaimer">
        <p className="text-sm text-muted-foreground">This resource is <b>educational</b>. Vue.js and its ecosystem evolve — always consult the latest official documentation before applying to production. Product names and trademarks belong to their respective owners.</p>
      </Section>
    </ReaderShell>
  );
}

// src/routes/_marketing.resources.read.react-beginner-guide.tsx
import { createFileRoute } from "@tanstack/react-router";
import { ReaderShell, Section, Figure, FAQItem, Callout, Code, References, type ReaderResource, type TocItem } from "@/components/resources/ReaderShell";

const RESOURCE: ReaderResource = {
  id: "react-beginner-guide",
  title: "React.js — Beginner Guide",
  category: "Web Development",
  difficulty: "Beginner",
  readingTime: "12 min",
  pages: 21,
  lastUpdated: "February 2026",
  tags: ["Web Development", "React", "Hooks"],
  heroImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1800&q=80",
  heroSubtitle: "A friendly first walk through React.js — JSX, components, props, state, events, conditional rendering, lists, hooks, routing, forms, and API integration with clear analogies and examples.",
};

const TOC: TocItem[] = [
  { id: "objectives", label: "Learning Objectives" },
  { id: "s1", label: "1. Why React?" },
  { id: "s2", label: "2. Setup & JSX" },
  { id: "s3", label: "3. Components & Props" },
  { id: "s4", label: "4. State & Events" },
  { id: "s5", label: "5. Conditional Rendering & Lists" },
  { id: "s6", label: "6. Hooks Introduction" },
  { id: "s7", label: "7. Routing" },
  { id: "s8", label: "8. Forms" },
  { id: "s9", label: "9. API Integration" },
  { id: "s10", label: "10. Best Practices" },
  { id: "s11", label: "11. Common Mistakes" },
  { id: "s12", label: "12. Tips & Tricks" },
  { id: "summary", label: "Summary" },
  { id: "faqs", label: "FAQs" },
  { id: "references", label: "References" },
  { id: "disclaimer", label: "Disclaimer" },
];

const RELATED = [
  { title: "React.js — Complete Tutorial", tag: "Web Development", time: "44 min" },
  { title: "React.js — Step-by-Step Learning Guide", tag: "Web Development", time: "23 min" },
  { title: "React.js — Cheat Sheet", tag: "Web Development", time: "5 min" },
];

export const Route = createFileRoute("/_marketing/resources/read/react-beginner-guide")({
  head: () => ({
    meta: [
      { title: `${RESOURCE.title} | EduNova AI` },
      { name: "description", content: RESOURCE.heroSubtitle },
      { property: "og:title", content: `${RESOURCE.title} | EduNova AI` },
      { property: "og:description", content: RESOURCE.heroSubtitle },
      { property: "og:image", content: RESOURCE.heroImage },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/resources/read/react-beginner-guide" }],
  }),
  component: Page,
});

function Page() {
  return (
    <ReaderShell resource={RESOURCE} toc={TOC} related={RELATED}>
      <Section id="objectives" title="Learning Objectives">
        <ul className="list-disc space-y-1 pl-5">
          <li>Understand what React is and why it dominates modern UI development.</li>
          <li>Read and write JSX, components, and props confidently.</li>
          <li>Manage state, handle events, and render lists correctly.</li>
          <li>Use core hooks — <code>useState</code>, <code>useEffect</code> — and route between pages.</li>
          <li>Integrate REST APIs and handle forms with validation.</li>
        </ul>
      </Section>

      <Section id="s1" title="1. Why React?">
        <p>React is a declarative JavaScript library for building user interfaces from reusable components. You describe <em>what</em> the UI should look like for any state, and React figures out <em>how</em> to update the DOM efficiently.</p>
        <Callout tone="info" title="Analogy">Think of React components like LEGO bricks — small, self-contained pieces you snap together into anything from a button to a full dashboard.</Callout>
      </Section>

      <Section id="s2" title="2. Setup & JSX">
        <Code lang="bash">{`npm create vite@latest my-app -- --template react
cd my-app && npm install && npm run dev`}</Code>
        <p>JSX lets you write HTML-like syntax inside JavaScript. Under the hood it compiles to <code>React.createElement</code> calls.</p>
        <Code lang="jsx">{`function Greeting() {
  const name = "Ada";
  return <h1>Hello, {name}!</h1>;
}`}</Code>
        <Figure src="https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1400&q=80" caption="Figure 1 — React renders a component tree into the DOM via a virtual DOM diff." />
      </Section>

      <Section id="s3" title="3. Components & Props">
        <p>Components are functions that return JSX. Props are inputs, like function arguments.</p>
        <Code lang="jsx">{`function Card({ title, children }) {
  return (
    <div className="card">
      <h2>{title}</h2>
      {children}
    </div>
  );
}
<Card title="Welcome"><p>Body text</p></Card>`}</Code>
      </Section>

      <Section id="s4" title="4. State & Events">
        <Code lang="jsx">{`import { useState } from "react";
function Counter() {
  const [n, setN] = useState(0);
  return <button onClick={() => setN(n + 1)}>Clicked {n}</button>;
}`}</Code>
        <Callout tone="warn" title="Never mutate state">Always create new objects/arrays — <code>setUser({ ...user, age: 30 })</code>, not <code>user.age = 30</code>.</Callout>
      </Section>

      <Section id="s5" title="5. Conditional Rendering & Lists">
        <Code lang="jsx">{`{isLoggedIn ? <Dashboard /> : <Login />}
{items.map((i) => <li key={i.id}>{i.name}</li>)}`}</Code>
        <p>Always provide a stable <code>key</code> when rendering lists — never the array index if items can reorder.</p>
      </Section>

      <Section id="s6" title="6. Hooks Introduction">
        <p><code>useState</code> stores state, <code>useEffect</code> runs side effects after render, <code>useRef</code> holds mutable values that survive renders.</p>
        <Code lang="jsx">{`useEffect(() => {
  document.title = \`Count: \${n}\`;
}, [n]);`}</Code>
      </Section>

      <Section id="s7" title="7. Routing">
        <p>TanStack Router or React Router lets you map URLs to components without a page reload.</p>
        <Code lang="jsx">{`<Routes>
  <Route path="/" element={<Home />} />
  <Route path="/about" element={<About />} />
</Routes>`}</Code>
        <Figure src="https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1400&q=80" caption="Figure 2 — Client-side routing swaps components under a persistent shell." />
      </Section>

      <Section id="s8" title="8. Forms">
        <Code lang="jsx">{`function LoginForm() {
  const [email, setEmail] = useState("");
  return <input value={email} onChange={(e) => setEmail(e.target.value)} />;
}`}</Code>
      </Section>

      <Section id="s9" title="9. API Integration">
        <Code lang="jsx">{`useEffect(() => {
  fetch("/api/users").then((r) => r.json()).then(setUsers);
}, []);`}</Code>
        <p>Prefer TanStack Query for production — it handles caching, retries, and background refresh.</p>
      </Section>

      <Section id="s10" title="10. Best Practices">
        <ul className="list-disc space-y-1 pl-5">
          <li>Keep components small and focused.</li>
          <li>Lift state up only when siblings need to share it.</li>
          <li>Use TypeScript for prop safety.</li>
          <li>Prefer composition over inheritance.</li>
        </ul>
      </Section>

      <Section id="s11" title="11. Common Mistakes">
        <table className="w-full border-collapse text-sm">
          <thead><tr><th className="border p-2 text-left">Mistake</th><th className="border p-2 text-left">Fix</th></tr></thead>
          <tbody>
            <tr><td className="border p-2">Mutating state directly</td><td className="border p-2">Return a new object with the setter</td></tr>
            <tr><td className="border p-2">Using array index as key</td><td className="border p-2">Use a stable unique id</td></tr>
            <tr><td className="border p-2">Missing useEffect deps</td><td className="border p-2">Add every referenced value or move it inside</td></tr>
          </tbody>
        </table>
      </Section>

      <Section id="s12" title="12. Tips & Tricks">
        <ul className="list-disc space-y-1 pl-5">
          <li>Install React DevTools browser extension.</li>
          <li>Use <code>strict mode</code> during development to catch side effects.</li>
          <li>Name event handlers with a <code>handle</code> prefix.</li>
        </ul>
      </Section>

      <Section id="summary" title="Summary & Key Takeaways">
        <p>React makes UI a function of state. Master components, props, state, and hooks, and everything else builds on top.</p>
      </Section>

      <Section id="faqs" title="FAQs">
        <FAQItem q="Do I need to know JavaScript first?">Yes — modern JS (ES6+, arrow functions, destructuring, async/await) is a prerequisite.</FAQItem>
        <FAQItem q="Class or function components?">Function components with hooks. Classes are legacy.</FAQItem>
        <FAQItem q="React or Next.js?">Learn React first, then add Next.js when you need SSR or file-based routing.</FAQItem>
      </Section>

      <Section id="references" title="Further Reading & References"><References /></Section>

      <Section id="disclaimer" title="Disclaimer">
        <p className="text-sm text-muted-foreground">Educational content. Verify APIs against the latest React documentation (react.dev).</p>
      </Section>
    </ReaderShell>
  );
}
